# See https://github.com/felleslosninger/github-workflows for reusable workflows used.

name: Deploy to systest from feature branch

on:
  workflow_dispatch: # manual trigger

jobs:
  build-publish-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-image.yml@main
    permissions:
      contents: write
      packages: write
      id-token: write
    with:
      image-name: digital-lommebok-oauth-server
      java-version: 25
      lifecycle: 'development'
    secrets: inherit

  call-update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    permissions:
      pull-requests: read
    needs: build-publish-image
    with:
      application-name: digital-lommebok-oauth-server
      deployment-environment: systest
      image-digest: ${{ needs.build-publish-image.outputs.image-digest }}
      image-name: digital-lommebok-oauth-server
      image-version: ${{ needs.build-publish-image.outputs.image-version }}
      kubernetes-repo: digital-lommebok-cd
      product-name: digital-lommebok
      lifecycle: 'development'
    secrets: inherit
