---
spring:
  application:
    environment: test

issuer-ui:
  issuer-server:
    base-url: https://utsteder.test.eidas2sandkasse.net
    credential-configurations:
      webuild-pid-mso-mdoc:
        id: "no.digdir.eudiw.webuild.pid_mso_mdoc"
        issuer: ${issuer-ui.issuer-server.base-url}/webuild
        title: Norsk ID-bevis WeBuild
        description: Norsk ID-bevis WeBuild (mdoc)
      webuild-pid-sd-jwt-vc:
        id: "no.digdir.eudiw.webuild.pid_sd_jwt_vc"
        issuer: ${issuer-ui.issuer-server.base-url}/webuild
        title: Norsk ID-bevis WeBuild
        description: Norsk ID-bevis WeBuild (SD-JWT VC)
