---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: digital-lommebok-auth-sources-connector
    environment: default
  data:
    redis:
      timeout: 3s
      connect-timeout: 3s

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

# Digdir standard logging
digdir:
  access:
    logging:
      debug-level: request
      filtering:
        static-resources: true
  audit:
    application-name:  ${spring.application.name}    # recommended naming convention is groupId:artifactId
    application-environment: ${spring.application.environment}
    filters:
      admin-header: false                                     # optional - default 'true'
      bearer-token: false                                    # optional - default 'true'
      ip-address: true                                    # optional - default 'true'
    prometheus:
      counter: false
  ## Eventlogging
  event:
    logging:
      feature-enabled: false

authoritative-sources-connector:
  features:
    allow-synthetic-pid: true
    allow-real-pid: false
  connectors:
    krr:
      uri: https://test.kontaktregisteret.no/
      scope: krr:global/kontaktinformasjon.read
      connect-timeout: 2s
      read-timeout: 2s
    advokatregisteret:
      uri: https://test-api.data.altinn.no/v1/directharvest/AdvRegPersonPrivat/
      subscription-key: ${ADVOKATREGISTERET_SUBSCRIPTION_KEY}
      scope: altinn:dataaltinnno/advregpersonprivat
      connect-timeout: 5s
      read-timeout: 5s
    inntektsapi:
      uri: https://inntekt.api.skatteetaten-test.no/
      scope: skatteetaten:inntekt
      connect-timeout: 2s
      read-timeout: 2s
    freg:
      uri: https://folkeregisteret-api-konsument.sits.no/folkeregisteret/offentlig-med-hjemmel/api/
      #uri: https://folkeregisteret.api.skatteetaten.no/folkeregisteret/offentlig-med-hjemmel/api # Prod
      connect-timeout: 5s
      read-timeout: 5s

# Maskinporten
maskinporten:
  lib:
    enabled: true
    issuer: https://test.maskinporten.no/
    clients:
      default:
        client-id: ${MASKINPORTEN_CLIENT_ID}
        kid: ${MASKINPORTEN_CLIENT_KID}
        issuer: ${maskinporten.lib.issuer}
        audience:
          - ${maskinporten.lib.issuer}
        token-endpoint: ${maskinporten.lib.issuer}token
        scope: krr:global/kontaktinformasjon.read altinn:dataaltinnno/advregpersonprivat folkeregister:deling/offentligmedhjemmel skatteetaten:inntekt
        connect-timeout-ms: 2000
        read-timeout-ms: 2000
        key-store-name: maskinporten-default


idporten-key-manager:
  keystores:
    maskinporten-default:
      key-store-type: JKS
      key-store-location: base64:${MASKINPORTEN_BASE64_KEYSTORE}
      key-store-password: ${MASKINPORTEN_KEYSTORE_PASSWORD}
      key-alias: ${MASKINPORTEN_KEYSTORE_ALIAS}
      key-password: ${MASKINPORTEN_KEY_PASSWORD}
