---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-issuer-server
    environment: default

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true

credential-issuer-server:
  cryptographic-bindings:
    - jwk
  formats:
    - mso_mdoc
  credential-configurations:
    - identifier: no.digdir.eudiw.pid_mso_mdoc
      scope: no.digdir.eudiw.pid_mso_mdoc
      format: mso_mdoc
      doctype: eu.europa.ec.eudi.pid.1
  claims-sources:
    - doctype: eu.europa.ec.eudi.pid.1
      display:
        - name: Norwegian PID
          locale: en
      claims:
        - path:
          - personal_administrative_number
          display:
            - name: Fnr/dnr
              locale: en
        - path:
            - given_name
          display:
            - name: Given name
              locale: en
