---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: digital-lommebok-issuer-server
    environment: default
  data:
    redis:
      timeout: 3s
      connect-timeout: 3s

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

credential-issuer-server:
  metadata-refresh-rate-in-millis: 30000 # 30 seconds (must be > cache TTL)
  features:
    pid-signing-keystore: pid-provider
  cryptographic-bindings:
    - jwk
  proof-signing-algorithms:
    - ES256
  credential-signing-algorithms:
    - ES256
  authoritative-sources:
    krr:
      uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/krr/credentialdata/retrieve
    freg:
      uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/freg/credentialdata/retrieve
    skatteetaten:
      uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/skatteetaten/credentialdata/retrieve
    advokatregisteret:
      uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/advokatregisteret/credentialdata/retrieve
  tenants:
    root:
      credential-configuration-sources-properties:
        - uri: classpath:credential-configurations/pid/pid_mso_mdoc.json
        - uri: classpath:credential-configurations/pid/pid_sd_jwt_vc.json
        - uri: classpath:credential-configurations/ageverification/proof_of_age_mso_mdoc.json
        - uri: classpath:credential-configurations/vegvesenet/mdl_mso_mdoc.json
        - uri: classpath:credential-configurations/advokattilsynet/advokatbevilling_mso_mdoc.json
        - uri: classpath:credential-configurations/krr/kontaktinformasjon_sd_jwt_vc.json
        - uri: classpath:credential-configurations/skatteetaten/inntekt_sd_jwt_vc.json
        - uri: ${byob-service.uri}
          api-key: ${byob-service.api-key}
          connect-timeout: 2s
          read-timeout: 2s
          cache-ttl: 28s

# Digdir standard logging
digdir:
  access:
    logging:
      debug-level: request
      filtering:
        static-resources: true
  audit:
    application-name:  ${spring.application.name}    # recommended naming convention is groupId:artifactId
    application-environment: ${spring.application.environment}
    filters:
      admin-header: false                                     # optional - default 'true'
      bearer-token: false                                    # optional - default 'true'
      ip-address: true                                    # optional - default 'true'
    prometheus:
      counter: false                                     # optional - default 'true'

## byob-service: Bring your own bevis service properties
byob-service:
  uri: http://digital-lommebok-byob-service-service:8080/v1/admin/credential-configurations
  api-key: ${API_KEY}
  connect-timeout: 2s
  read-timeout: 2s
  cache-ttl: 28s

idporten-key-manager:
  keystores:
    pid-provider:
      key-store-type: ${PID_PROVIDER_KEYSTORE_TYPE}
      key-store-location: ${PID_PROVIDER_KEYSTORE_LOCATION}
      key-store-password: ${PID_PROVIDER_KEYSTORE_PASSWORD}
      key-alias: ${PID_PROVIDER_KEYSTORE_KEY_ALIAS}
      key-password: ${PID_PROVIDER_KEYSTORE_KEY_PASSWORD}
    eaa-provider:
      key-store-type: ${EAA_PROVIDER_KEYSTORE_TYPE}
      key-store-location: ${EAA_PROVIDER_KEYSTORE_LOCATION}
      key-store-password: ${EAA_PROVIDER_KEYSTORE_PASSWORD}
      key-alias: ${EAA_PROVIDER_KEYSTORE_KEY_ALIAS}
      key-password: ${EAA_PROVIDER_KEYSTORE_KEY_PASSWORD}
