---
spring:
  application:
    environment: systest
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

credential-issuer-server:
  credential-issuer: https://utsteder.eidas2sandkasse.dev
  authorization-servers:
    - id: auth-eidas2sandkasse
      issuer: https://auth.eidas2sandkasse.dev
      jwks-uri: http://digital-lommebok-oauth-server-service:8080/jwks
      internal-api:
        uri: http://digital-lommebok-oauth-server-service:8080
        api-key-header: X-API-KEY
        api-key: ${AUTH_PROXY_API_KEY}
  pre-authorization-servers:
    - id: maskinporten
      issuer: https://test.maskinporten.no/
      jwks-uri: https://test.maskinporten.no/jwk
  authoritative-sources:
    krr:
      api:
        uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/krr/credentialdata/retrieve
        api-key-header: X-API-KEY
        api-key: ${AUTH_SOURCE_KRR_API_KEY}
    freg:
      api:
        uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/freg/credentialdata/retrieve
        api-key-header: X-API-KEY
        api-key: ${AUTH_SOURCE_FREG_API_KEY}
    skatteetaten:
      api:
        uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/skatteetaten/credentialdata/retrieve
        api-key-header: X-API-KEY
        api-key: ${AUTH_SOURCE_SKATTEETATEN_API_KEY}
    advokatregisteret:
      api:
        uri: http://digital-lommebok-auth-sources-connector-service:8080/api/v1/advokatregisteret/credentialdata/retrieve
        api-key-header: X-API-KEY
        api-key: ${AUTH_SOURCE_ADVOKATREGISTERET_API_KEY}
  tenants:
    bevisgenerator:
      display-names:
        "no": "Digdir bevisgenerator"
      credential-configuration-sources-properties:
        - local:
            paths:
              - classpath:credential-configurations/ageverification/proof_of_age_mso_mdoc.json
              - classpath:credential-configurations/vegvesenet/mdl_mso_mdoc.json
              - classpath:credential-configurations/advokattilsynet/advokatbevilling_mso_mdoc.json
              - classpath:credential-configurations/krr/kontaktinformasjon_sd_jwt_vc.json
              - classpath:credential-configurations/skatteetaten/inntekt_sd_jwt_vc.json
        - api:
            uri: http://digital-lommebok-byob-service-service:8080/v1/admin/credential-configurations
            api-key-header: X-API-KEY
            api-key: ${API_KEY}
            connect-timeout: 2s
            read-timeout: 2s
    pid:
      display-names:
        "no": "PID-utsteder (Norsk ID-bevis)"
      credential-configuration-sources-properties:
        - local:
            paths:
              - classpath:credential-configurations/pid/pid_mso_mdoc.json
              - classpath:credential-configurations/pid/pid_sd_jwt_vc.json
    minid:
      display-names:
        "no": "MinID bevisutsteder"
      credential-configuration-sources-properties:
        - local:
            paths:
              - classpath:credential-configurations/minid/mpid_sd_jwt_vc.json


idporten-key-manager:
  keystores:
    pid-provider:
      key-store-type: ${PID_PROVIDER_KEYSTORE_TYPE}
      key-store-location: ${PID_PROVIDER_KEYSTORE_LOCATION}
      key-store-password: ${PID_PROVIDER_KEYSTORE_PASSWORD}
      key-alias: ${PID_PROVIDER_KEYSTORE_KEY_ALIAS}
      key-password: ${PID_PROVIDER_KEYSTORE_KEY_PASSWORD}
    eaa-provider:
      key-store-type: ${EAA_PROVIDER_KEYSTORE_TYPE}
      key-store-location: ${EAA_PROVIDER_KEYSTORE_LOCATION}
      key-store-password: ${EAA_PROVIDER_KEYSTORE_PASSWORD}
      key-alias: ${EAA_PROVIDER_KEYSTORE_KEY_ALIAS}
      key-password: ${EAA_PROVIDER_KEYSTORE_KEY_PASSWORD}
    minid-provider:
      key-store-type: ${MINID_PROVIDER_KEYSTORE_TYPE}
      key-store-location: ${MINID_PROVIDER_KEYSTORE_LOCATION}
      key-store-password: ${MINID_PROVIDER_KEYSTORE_PASSWORD}
      key-alias: ${MINID_PROVIDER_KEYSTORE_KEY_ALIAS}
      key-password: ${MINID_PROVIDER_KEYSTORE_KEY_PASSWORD}