---
spring:
  application:
    environment: systest

credential-issuer-server:
  credential-issuer: https://utsteder.eidas2sandkasse.dev
  authorization-servers:
    - issuer: https://auth.eidas2sandkasse.dev
      jwks-uri: https://auth.eidas2sandkasse.dev/jwks
