---
spring:
  application:
    environment: systest

credential-issuer-server:
  credential-issuer: https://utsteder.eidas2sandkasse.dev
  authorization-servers:
    - issuer: https://auth.eidas2sandkasse.dev
      jwks-uri: http://digital-lommebok-oauth-server-service:8080/jwks
      api-key: ${AUTH_PROXY_API_KEY}
  pre-authorization-servers:
    - issuer: https://test.maskinporten.no/
      jwks-uri: https://test.maskinporten.no/jwk

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
