---
spring:
  application:
    environment: test
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

credential-issuer-server:
  credential-issuer: https://utsteder.test.eidas2sandkasse.net
  authorization-servers:
    - id: auth-eidas2sandkasse
      issuer: https://auth.test.eidas2sandkasse.net
      jwks-uri: http://digital-lommebok-oauth-server-service:8080/jwks
      internal-api:
        uri: http://digital-lommebok-oauth-server-service:8080
        api-key-header: X-API-KEY
        api-key: ${AUTH_PROXY_API_KEY}
  pre-authorization-servers:
    - id: maskinporten
      issuer: https://test.maskinporten.no/
      jwks-uri: https://test.maskinporten.no/jwk
