---
server:
  port: 8080

spring:
  thread-executor: virtual
  application:
    name: eudiw-issuer-server
    environment: default

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: info,version,prometheus,health
      base-path: /
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: ${spring.application.environment}

credential-issuer-server:
  cryptographic-bindings:
    - jwk
  formats:
    - mso_mdoc
  credential-configurations:
    - identifier: no.digdir.eudiw.pid_mso_mdoc
      scope: nobid:pid
      format: mso_mdoc
      doctype: eu.europa.ec.eudi.pid.1
      authorization-server: ${credential-issuer-server.authorization-servers[0].issuer}
  claims-sources:
    - doctype: eu.europa.ec.eudi.pid.1
      class-name: no.idporten.eudiw.issuer.claimssource.pid.PIDClaimsSource
  key-store:
    type: ${ISSUER_KEYSTORE_TYPE}
    location: ${ISSUER_KEYSTORE_LOCATION}
    password: ${ISSUER_KEYSTORE_PASSWORD}
    key-alias: ${ISSUER_KEYSTORE_KEY_ALIAS}
    key-password: ${ISSUER_KEYSTORE_KEY_PASSWORD}
