---
server:
  port: 9240

management:
  server:
    port: 9241

spring:
  application:
    environment: docker

credential-issuer-server:
  credential-issuer: http://digital-lommebok-issuer-server:9240
  authorization-servers:
    - issuer: https://auth.eidas2sandkasse.dev
      jwks-uri: https://auth.eidas2sandkasse.dev/jwks
