---
spring:
  application:
    environment: test

bevisgenerator:
  features:
    allow-bevistyper-v2: true
    revocation-v2-rich-result: true
  byob-service:
    base-url: https://byob-service.test.eidas2sandkasse.net
  issuer-server:
    credential-issuer: https://utsteder.test.eidas2sandkasse.net/bevisgenerator
    credential-issuer-pid: https://utsteder.test.eidas2sandkasse.net/pid
    credential-issuer-minid: https://utsteder.test.eidas2sandkasse.net/minid
    credential-issuer-webuild: https://utsteder.test.eidas2sandkasse.net/webuild
    well-known-urls:
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/pid
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/minid
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/bevisgenerator
      - https://utsteder.test.eidas2sandkasse.net/.well-known/openid-credential-issuer/webuild
    subject-credential-configurations:
      - credential-configuration-id: no.digdir.eudiw.pid_mso_mdoc
        credential-issuer: ${bevisgenerator.issuer-server.credential-issuer-pid}
        description: Norsk ID-bevis (mdoc)
        scope: eudiw:no:pid
      - credential-configuration-id: no.digdir.eudiw.pid_sd_jwt_vc
        credential-issuer: ${bevisgenerator.issuer-server.credential-issuer-pid}
        description: Norsk ID-bevis (SD-JWT VC)
        scope: eudiw:no:pid
      - credential-configuration-id: no.digdir.eudiw.webuild.pid_mso_mdoc
        credential-issuer: ${bevisgenerator.issuer-server.credential-issuer-webuild}
        description: Norsk ID-bevis WeBuild (mdoc)
        scope: eudiw:no:pid
      - credential-configuration-id: no.digdir.eudwi.webuild.pid_sd_jwt_vc
        credential-issuer: ${bevisgenerator.issuer-server.credential-issuer-webuild}
        description: Norsk ID-bevis WeBuild (SD-JWT VC)
        scope: eudiw:no:pid
    verifier-service:
    base-url: https://verifier-service.test.eidas2sandkasse.net

maskinporten:
  lib:
    issuer: https://test.maskinporten.no/
