---
server:
  port: 9283
  servlet:
    session:
      cookie:
        secure: false
management:
  server:
    port: 9283
  endpoint:
    health:
      show-details: always

spring:
  application:
    environment: docker
  data:
    redis:
      port: 6379
      host: redis

eudiw-idporten-login:
  features:
    allow-synthetic-person-identifiers: true
    allow-real-person-identifiers: false
  oidc-sdk:
    issuer: http://eudiw-idporten-login:9283/
    clients:
      - client-id: testclient
        client-secret: secret
        scopes:
          - openid
        redirect-uris:
          - http://testclient:8888/authorize/response
          - http://localhost:8888/authorize/response
          - http://127.0.0.1:8888/authorize/response
