---
spring:
  application:
    environment: systest
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

# EUDIW auth server
oauth-authorization-server:
  issuer: https://auth.eidas2sandkasse.dev
  access-token-default-audience: https://utsteder.eidas2sandkasse.dev

oidc-proxy:

  # webuild
  headless-login:
    enabled: true
    synthetic_pid: 16903349844
    acr: idporten-loa-high
    client-ids:
      - wallet-client
