<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.6</version>
        <relativePath/>
    </parent>
    <groupId>no.idporten.eudiw</groupId>
    <artifactId>issuer-server</artifactId>
    <version>DEV-SNAPSHOT</version>
    <name>issuer-server</name>
    <description>Digdir utferdar for norsk eidas2sandkasse</description>

    <properties>
        <java.version>25</java.version>
        <kotlin.version>2.2.20</kotlin.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <properties-maven-plugin.version>1.2.1</properties-maven-plugin.version>
        <lombok.version>1.18.42</lombok.version>
        <idporten-actuator-starter.version>2.0.0</idporten-actuator-starter.version>
        <idporten-access-log.version>2.8.0</idporten-access-log.version>
        <opentelemetry-api.version>1.55.0</opentelemetry-api.version>
        <jakarta.xml.bind-api.version>4.0.2</jakarta.xml.bind-api.version>
        <springdoc.version>2.8.13</springdoc.version>
        <bcpkix-jdk18on.version>1.82</bcpkix-jdk18on.version>
        <bcprov-jdk18on.version>1.82</bcprov-jdk18on.version>
        <nimbus-jose-jwt.version>10.5</nimbus-jose-jwt.version>
        <oauth2-oidc-sdk.version>11.29.2</oauth2-oidc-sdk.version>
        <waltid-mdoc-credentials-jvm.version>0.15.1</waltid-mdoc-credentials-jvm.version>
        <waltid-sdjwt-jvm.version>0.15.1</waltid-sdjwt-jvm.version>
        <cose-java.version>1.1.1-SNAPSHOT</cose-java.version>
        <kotlinx-serialization-bom.version>1.9.0</kotlinx-serialization-bom.version>
        <kotlinx-coroutines-core.version>1.10.2</kotlinx-coroutines-core.version>
        <kotlinx-datetime-jvm.version>0.7.1-0.6.x-compat</kotlinx-datetime-jvm.version>
        <kotlinx-serialization-json-jvm.version>1.9.0</kotlinx-serialization-json-jvm.version>

        <freg-integration-lib.version>1.0.9</freg-integration-lib.version>
        <maskinporten.client.version>5.0.1</maskinporten.client.version>
        <log-event.version>1.5.1</log-event.version>
        <idporten-log-audit.version>2.5.3</idporten-log-audit.version>

    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>no.idporten.actuator</groupId>
            <artifactId>idporten-actuator-starter</artifactId>
            <version>${idporten-actuator-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>no.idporten.logging</groupId>
            <artifactId>idporten-access-log-spring-boot-3-starter</artifactId>
            <version>${idporten-access-log.version}</version>
        </dependency>
        <dependency>
            <groupId>no.idporten.logging</groupId>
            <artifactId>idporten-log-audit-spring-boot-3-starter</artifactId>
            <version>${idporten-log-audit.version}</version>
        </dependency>
        <dependency>
            <groupId>no.digdir.logging</groupId>
            <artifactId>log-event-spring-boot-starter</artifactId>
            <version>${log-event.version}</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
            <version>${opentelemetry-api.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>nimbus-jose-jwt</artifactId>
            <version>${nimbus-jose-jwt.version}</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>${oauth2-oidc-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>id.walt.mdoc-credentials</groupId>
            <artifactId>waltid-mdoc-credentials-jvm</artifactId>
            <version>${waltid-mdoc-credentials-jvm.version}</version>
        </dependency>
        <dependency>
            <groupId>id.walt.sdjwt</groupId>
            <artifactId>waltid-sdjwt-jvm</artifactId>
            <version>${waltid-sdjwt-jvm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.cose</groupId>
            <artifactId>cose-java</artifactId>
            <version>${cose-java.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>${bcpkix-jdk18on.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>${bcprov-jdk18on.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-datetime-jvm</artifactId>
            <version>${kotlinx-datetime-jvm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-bom</artifactId>
            <version>${kotlinx-serialization-bom.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-json-jvm</artifactId>
            <version>${kotlinx-serialization-json-jvm.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <version>${kotlinx-coroutines-core.version}</version>
            <type>pom</type>
        </dependency>
        <!-- Move to claims-source application for PID -->
        <dependency>
            <groupId>no.digdir.freg</groupId>
            <artifactId>freg-integration-lib</artifactId>
            <version>${freg-integration-lib.version}</version>
        </dependency>
        <dependency>
            <groupId>no.idporten</groupId>
            <artifactId>lib-maskinporten-client</artifactId>
            <version>${maskinporten.client.version}</version>
        </dependency>
        <!-- end: Move to claims-source -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <source>src/main/java</source>
                                <source>target/generated-sources/annotations</source>
                                <source>src/test/kotlin</source>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <source>src/test/java</source>
                                <source>target/generated-test-sources/test-annotations</source>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>24</jvmTarget>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmArguments>-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9245</jvmArguments>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <proc>full</proc>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
        <repository>
            <id>github</id>
            <name>GitHub felleslosninger Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/felleslosninger/.github</url>
        </repository>
        <repository>
            <id>waltid-releases</id>
            <name>Waltid Release Repository</name>
            <url>https://maven.waltid.dev/releases</url>
        </repository>
        <repository>
            <id>waltid-snapshots</id>
            <name>Waltid Snapshot Repository</name>
            <url>https://maven.waltid.dev/snapshots</url>
        </repository>
    </repositories>

</project>
