---
spring:
  application:
    environment: test

verifier-proxy:
  siop2-client-id: verifier-proxy.test.eidas2sandkasse.net
  client-identifier-scheme: x509_hash
  external-base-uri: https://verifier-proxy.test.eidas2sandkasse.net
  credential-issuers:
    - https://utsteder.test.eidas2sandkasse.net
