---
spring:
  application:
    environment: test

  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

verifier-service:
  siop2-client-id: verifier-service.test.eidas2sandkasse.net
  external-base-uri: https://verifier-service.test.eidas2sandkasse.net
  client-applications:
    idporten-login:
      keystore-name: idporten-login-access


idporten-key-manager:
  keystores:
    idporten-login-access:
      key-store-type: ${IDPORTEN_LOGIN_ACCESS_KEYSTORE_TYPE}
      key-store-location: ${IDPORTEN_LOGIN_ACCESS_KEYSTORE_LOCATION}
      key-store-password: ${IDPORTEN_LOGIN_ACCESS_KEYSTORE_PASSWORD}
      key-alias: ${IDPORTEN_LOGIN_ACCESS_KEY_ALIAS}
      key-password: ${IDPORTEN_LOGIN_ACCESS_KEY_PASSWORD}
