---
spring:
  application:
    environment: test

  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

verifier-service:
  siop2-client-id: verifier-service.test.eidas2sandkasse.net
  external-base-uri: https://verifier-service.test.eidas2sandkasse.net
  client-applications:
    idporten-login:
      keystore-name: idporten-login-access
    bevisgenerator-login:
      keystore-name: bevisgenerator-login-access
    ks-hackathon:
      keystore-name: ks-hackathon-access
      disabled: true


idporten-key-manager:
  keystores:
    idporten-login-access:
      key-store-type: ${IDPORTEN_LOGIN_ACCESS_KEYSTORE_TYPE}
      key-store-location: ${IDPORTEN_LOGIN_ACCESS_KEYSTORE_LOCATION}
      key-store-password: ${IDPORTEN_LOGIN_ACCESS_KEYSTORE_PASSWORD}
      key-alias: ${IDPORTEN_LOGIN_ACCESS_KEY_ALIAS}
      key-password: ${IDPORTEN_LOGIN_ACCESS_KEY_PASSWORD}
    bevisgenerator-login-access:
      key-store-type: ${BEVISGENERATOR_LOGIN_ACCESS_KEYSTORE_TYPE}
      key-store-location: ${BEVISGENERATOR_LOGIN_ACCESS_KEYSTORE_LOCATION}
      key-store-password: ${BEVISGENERATOR_LOGIN_ACCESS_KEYSTORE_PASSWORD}
      key-alias: ${BEVISGENERATOR_LOGIN_ACCESS_KEY_ALIAS}
      key-password: ${BEVISGENERATOR_LOGIN_ACCESS_KEY_PASSWORD}
    ks-hackathon-access:
      key-store-type: ${KS_HACKATHON_ACCESS_KEYSTORE_TYPE}
      key-store-location: ${KS_HACKATHON_ACCESS_KEYSTORE_LOCATION}
      key-store-password: ${KS_HACKATHON_ACCESS_KEYSTORE_PASSWORD}
      key-alias: ${KS_HACKATHON_ACCESS_KEY_ALIAS}
      key-password: ${KS_HACKATHON_ACCESS_KEY_PASSWORD}

trustlists:
  connect-timeout: 3s
  read-timeout: 3s
  environments:
    eidas2sandkasse:
      pid: https://tillitsliste.test.eidas2sandkasse.net/no_eidas2sandkasse_test_pid.jws
      attestations: https://tillitsliste.test.eidas2sandkasse.net/no_eidas2sandkasse_test_tsl.xtsl