---
spring:
  application:
    environment: prod

verifier-service:
  siop2-client-id: verifier-service.eidas2sandkasse.no
  external-base-uri: https://verifier-service.eidas2sandkasse.no

trustlists:
  connect-timeout: 3s
  read-timeout: 3s
  issuer-trustlists:
    "[https://utsteder.eidas2sandkasse.net/pid]": https://tillitsliste.eidas2sandkasse.net/no_eidas2sandkasse_prod_pid.jws
    default: https://tillitsliste.eidas2sandkasse.net/no_eidas2sandkasse_prod_tsl.xtsl
  named-trustlists:
    "[eidas2sandkasse-pid]": https://tillitsliste.eidas2sandkasse.net/no_eidas2sandkasse_prod_pid.jws
    "[eidas2sandkasse.xtsl]": https://tillitsliste.eidas2sandkasse.net/no_eidas2sandkasse_prod_tsl.xtsl
  pid:
    - eidas2sandkasse-pid
  attestations:
    - eidas2sandkasse.xtsl