<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
    </parent>
    <groupId>no.idporten.eudiw</groupId>
    <artifactId>eudiw-idporten-login</artifactId>
    <version>DEV-SNAPSHOT</version>
    <name>eudiw-idporten-login</name>
    <description>EUDIW ID-porten login</description>
    <properties>
        <java.version>25</java.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <idporten-actuator-starter.version>3.1.1</idporten-actuator-starter.version>
        <idporten-access-log.version>4.0.4</idporten-access-log.version>
        <idporten-audit-version>4.0.4</idporten-audit-version>
        <idporten-validators.version>1.6.1</idporten-validators.version>
        <idporten-lib-keystore-spring-boot-4.version>3.0.0</idporten-lib-keystore-spring-boot-4.version>
        <opentelemetry-api.version>1.65.0</opentelemetry-api.version>
        <surefire.plugin.version>3.5.3</surefire.plugin.version>
        <idporten-oidc-server-redis-cache-starter.version>2.0.0</idporten-oidc-server-redis-cache-starter.version>
        <oauth2-oidc-sdk.version>11.38.2</oauth2-oidc-sdk.version>
        <bcpkix-jdk18on.version>1.85</bcpkix-jdk18on.version>
        <bcprov-jdk18on.version>1.85.2</bcprov-jdk18on.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>no.idporten.validators</groupId>
            <artifactId>idporten-validators</artifactId>
            <version>${idporten-validators.version}</version>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>no.idporten.actuator</groupId>
            <artifactId>idporten-actuator-4-starter</artifactId>
            <version>${idporten-actuator-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-core</artifactId>
        </dependency>
        <dependency>
            <groupId>no.idporten.logging</groupId>
            <artifactId>idporten-access-log-spring-boot-4-starter</artifactId>
            <version>${idporten-access-log.version}</version>
        </dependency>
        <dependency>
            <groupId>no.idporten.logging</groupId>
            <artifactId>idporten-log-audit-spring-boot-4-starter</artifactId>
            <version>${idporten-audit-version}</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
            <version>${opentelemetry-api.version}</version>
        </dependency>
        <dependency>
            <groupId>no.digdir</groupId>
            <artifactId>idporten-oidc-server-redis-cache-spring-boot-4-starter</artifactId>
            <version>${idporten-oidc-server-redis-cache-starter.version}</version>
        </dependency>
        <dependency>
            <groupId>no.idporten</groupId>
            <artifactId>idporten-lib-keystore-spring-boot-4</artifactId>
            <version>${idporten-lib-keystore-spring-boot-4.version}</version>
        </dependency>
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>${oauth2-oidc-sdk.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
            <version>${bcpkix-jdk18on.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>${bcprov-jdk18on.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <version>1.5.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <proc>full</proc>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub felleslosninger Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/felleslosninger/.github</url>
        </repository>
        <repository>
            <id>waltid-repository-releases</id>
            <name>walt.id Release Repository</name>
            <url>https://maven.waltid.dev/releases</url>
        </repository>
        <repository>
            <id>waltid-repository-snapshots</id>
            <name>walt.id Snapshot Repository</name>
            <url>https://maven.waltid.dev/snapshots</url>
        </repository>
    </repositories>
</project>
